"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
[character]
format = "[\\$](green bold) "

[directory]
truncation_length = 3

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = '🔥'
staged = ''
renamed = ''
deleted = ''

[python]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[java]
disabled = true

[cmd_duration]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[c]
disabled = true
